### ISSUE TITLE
Requires Qt6, not 5

### ISSUE THREAD

**Issue by palfrey** [Martchus/syncthingtray#381]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Android app or mobile UI in general
* [x] Backend libraries

**Environment and versions**
* syncthingtray: 2.0.2
* Qt version: 5.15.1

**Bug description**
The README claims 5 support, but you get
```
/src/syncthingconnector/syncthingconfig.cpp: In function 'QJsonValue Data::xmlValueToJsonValue(QStringView)':
/src/syncthingconnector/syncthingconfig.cpp:96:25: error: 'class QStringView' has no member named 'toDouble'
96 |     auto number = value.toDouble(&isNumber);
```
and https://doc.qt.io/qt-6/qstringview.html#toDouble says that's a 6.x feature

**Steps to reproduce**
1. Build with qt5

**Comment by Martchus** [comment]
This should probably be fixed then as this function has only been added in 5.15.2, see https://doc.qt.io/archives/qt-5.15/qstringview.html#toDouble.

**Comment by Martchus** [comment]
I fixed this but haven't tested it yet. Not sure what the lowest Qt 5 version is now but it should now compile with your 5.15.1.

**Comment by palfrey** [comment]
Builds fine now, thanks
